name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Format-Lint-TypeCheck:
    name: Format, Lint and TypeCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Format
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

      - name: Type Check
        run: pnpm run typecheck

      - name: Run Unit Tests
        run: pnpm run test

  Test:
    name: Small Test
    strategy:
      fail-fast: false
      matrix:
        os:
          # https://github.com/actions/runner-images
          - windows-latest
          - ubuntu-latest
          - ubuntu-24.04-arm
        method:
          - local
          - network
          - auto
    uses: ./.github/workflows/_test.yml
    secrets: inherit
    with:
      os: ${{ matrix.os }}
      version: 'latest'
      method: ${{ matrix.method }}
      debug: true

  ci-check:
    name: CI Status Check
    runs-on: ubuntu-latest
    needs: [Format-Lint-TypeCheck, Test]
    if: always()
    steps:
      - name: Some CI failed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')}}
        run: exit 1
      - name: All CI passed
        if: ${{ contains(needs.*.result, 'success') }}
        run: exit 0
